name: CI
on:
    push:
        branches: [master]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js environment
              uses: actions/setup-node@v1.4.2
              with:
                  node-version: 12.x
            - name: Install dependencies
              run: |
                  yarn
            - name: Deploy Sanity
              run: |
                  set -e
                  # Put your environment variables here. Don't forget
                  # to create secrets for them on GitHub:
                  # https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
                  cat << EOF > .env.production
                  SANITY_STUDIO_FRONTEND_PREVIEW_SECRET=${{ secrets.SANITY_STUDIO_FRONTEND_PREVIEW_SECRET }}
                  SANITY_STUDIO_FRONTEND_BASE_URL=${{ secrets.SANITY_STUDIO_FRONTEND_BASE_URL }}
                  EOF
                  # Make sure to add a secret for SANITY_AUTH_TOKEN
                  SANITY_AUTH_TOKEN="${{ secrets.SANITY_AUTH_TOKEN }}" yarn sanity deploy